### PR TITLE
Add custom tag directive on vddl-draggable component

### PR DESCRIPTION
**Pull request by ChucKN0risK**
This allow the user to change the rendered HTML of the vddl-draggable component.

### CODE REVIEW

**Comment by hejianxian** [comment]
@ChucKN0risK 

👍Thank you for your PR, Could you please add this attribute to other components? 😄

**Comment by ChucKN0risK** [comment]
Will do ;)

**Comment by ChucKN0risK** [comment]
Done ;)

**Comment by hejianxian** [comment]
Thank you! 👍

**Pull request merged**
